kind = "mobile"
previewPath = "/mobile/"
title = "OTP Mobile App"
version = "1.0.0"
id = "artifacts/otp-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 24514

[services.development]
run = "pnpm --filter @workspace/otp-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/otp-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/otp-mobile", "run", "serve" ]

[services.env]
PORT = "24514"
BASE_PATH = "/mobile/"
